language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer install

before_script:
  - composer self-update
  - composer install --prefer-source
  - if [ "$TRAVIS_PHP_VERSION" = "hhvm" -o "$TRAVIS_PHP_VERSION" = "hhvm-nightly" ]; then rm phpspec.yml; fi

script:
  - mkdir .reports
  # Code style
  - php vendor/bin/phpcs ./Config/ ./EventListener/ ./Form ./Integration/ ./Views/ --standard=PSR1 --encoding=utf-8 --report=summary
  - php vendor/bin/phpcs ./Config/ ./EventListener/ ./Form ./Integration/ ./Views/ --standard=PSR2 --encoding=utf-8 --report=summary
  - composer phpstan
  - bin/php-cs-fixer fix --config=.php_cs -v --dry-run --using-cache=no --show-progress=dots --diff $(git diff -- '*.php' --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")

after_success:
  # Send coverage
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./coverage.xml
